---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.6.0
  environment:
    CROSS: 'true'
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - dapper ci
  - echo "${DRONE_TAG}-amd64" | sed -e 's/+/-/g' >.tags
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
      exclude:
        - refs/tags/chart-*

- name: package-chart
  image: rancher/dapper:v0.6.0
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - dapper package-chart
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
    - refs/tags/chart-*
    instance:
    - drone-publish.rancher.io
    event:
    - tag

- name: release-chart
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum.txt
    checksum_flatten: true
    files:
    - "deploy/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      include:
      - refs/tags/chart-*  
    event:
    - tag

- name: index-chart
  image: rancher/dapper:v0.6.0
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - dapper index-chart
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    ref:
    - refs/tags/chart-*
    instance:
    - drone-publish.rancher.io
    event:
    - tag

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "bin/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      include:
      - refs/head/master
      - refs/tags/*
      exclude:
      - refs/tags/chart-*  
    event:
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/k3k"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      include:
      - refs/head/master
      - refs/tags/*
      exclude:
      - refs/tags/chart-*  
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: manifest

platform:
  os: linux
  arch: amd64

steps:
  - name: push-runtime-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest-runtime.tmpl
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      ref:
        include:
        - refs/head/master
        - refs/tags/*
        exclude:
        - refs/tags/chart-*  
depends_on:
  - amd64
