{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k3k.serviceAccountName" . }}
  labels:
    {{- include "k3k.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
