apiVersion: v1
kind: Service
metadata: 
  name: k3k-webhook
  labels:
    {{- include "k3k.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      name: https-webhook
      targetPort: 9443
  selector:
    {{- include "k3k.selectorLabels" . | nindent 6 }}
