apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: hcp-server
spec:
  mode: hcp
  tlsSANs:
    - "<externally-reachable-node-ip-or-dns>"
  servers: 1
  version: v1.33.1-k3s1
  expose:
    nodePort: {}
