apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: single-server
spec:
  mode: "shared"
  servers: 1
  agents: 3
  token: test
  version: v1.26.0-k3s2
  clusterCIDR: 10.30.0.0/16
  serviceCIDR: 10.31.0.0/16
  clusterDNS: 10.30.0.10
  serverArgs:
  - "--write-kubeconfig-mode=777"
  expose:
    ingress:
      enabled: true
      ingressClassName: "nginx"
