== API Reference

=== Packages

* <<k3kiov1beta1, k3k.io/v1beta1>>

=== k3k.io/v1beta1

==== Resource Types

* <<cluster, Cluster>>
* <<clusterlist, ClusterList>>
* <<virtualclusterpolicy, VirtualClusterPolicy>>
* <<virtualclusterpolicylist, VirtualClusterPolicyList>>

===== Addon

Addon specifies a Secret containing YAML to be deployed on cluster
startup.

_Appears in:_ - <<clusterspec, ClusterSpec>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+secretNamespace+` _string_ |SecretNamespace is the namespace of the
Secret. | |

|`+secretRef+` _string_ |SecretRef is the name of the Secret. | |
|===

===== Cluster

Cluster defines a virtual Kubernetes cluster managed by k3k. It
specifies the desired state of a virtual cluster, including version,
node configuration, and networking. k3k uses this to provision and
manage these virtual clusters.

_Appears in:_ - <<clusterlist, ClusterList>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+apiVersion+` _string_ |`+k3k.io/v1beta1+` | |

|`+kind+` _string_ |`+Cluster+` | |

|`+metadata+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#objectmeta-v1-meta[ObjectMeta]_
|Refer to Kubernetes API documentation for fields of `+metadata+`. | |

|`+spec+` _<<clusterspec, ClusterSpec>>_ |Spec defines the desired state
of the Cluster. |{ } |
|===

===== ClusterList

ClusterList is a list of Cluster resources.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+apiVersion+` _string_ |`+k3k.io/v1beta1+` | |

|`+kind+` _string_ |`+ClusterList+` | |

|`+metadata+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#listmeta-v1-meta[ListMeta]_
|Refer to Kubernetes API documentation for fields of `+metadata+`. | |

|`+items+` _<<cluster, Cluster>> array_ | | |
|===

===== ClusterMode

_Underlying type:_ _string_

ClusterMode is the possible provisioning mode of a Cluster.

_Validation:_ - Enum: [shared virtual]

_Appears in:_ - <<clusterspec, ClusterSpec>> -
<<virtualclusterpolicyspec, VirtualClusterPolicySpec>>

===== ClusterPhase

_Underlying type:_ _string_

ClusterPhase is a high-level summary of the cluster’s current lifecycle
state.

_Appears in:_ - <<clusterstatus, ClusterStatus>>

===== ClusterSpec

ClusterSpec defines the desired state of a virtual Kubernetes cluster.

_Appears in:_ - <<cluster, Cluster>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+version+` _string_ |Version is the K3s version to use for the virtual
nodes.It should follow the K3s versioning convention (e.g.,
v1.28.2-k3s1).If not specified, the Kubernetes version of the host node
will be used. | |

|`+mode+` _<<clustermode, ClusterMode>>_ |Mode specifies the cluster
provisioning mode: "`shared`" or "`virtual`".Defaults to "`shared`".
This field is immutable. |shared |Enum: [shared virtual]

|`+servers+` _integer_ |Servers specifies the number of K3s pods to run
in server (control plane) mode.Must be at least 1. Defaults to 1. |1 |

|`+agents+` _integer_ |Agents specifies the number of K3s pods to run in
agent (worker) mode.Must be 0 or greater. Defaults to 0.This field is
ignored in "`shared`" mode. |0 |

|`+clusterCIDR+` _string_ |ClusterCIDR is the CIDR range for pod
IPs.Defaults to 10.42.0.0/16 in shared mode and 10.52.0.0/16 in virtual
mode.This field is immutable. | |

|`+serviceCIDR+` _string_ |ServiceCIDR is the CIDR range for service
IPs.Defaults to 10.43.0.0/16 in shared mode and 10.53.0.0/16 in virtual
mode.This field is immutable. | |

|`+clusterDNS+` _string_ |ClusterDNS is the IP address for the CoreDNS
service.Must be within the ServiceCIDR range. Defaults to
10.43.0.10.This field is immutable. | |

|`+persistence+` _<<persistenceconfig, PersistenceConfig>>_ |Persistence
specifies options for persisting etcd data.Defaults to dynamic
persistence, which uses a PersistentVolumeClaim to provide data
persistence.A default StorageClass is required for dynamic persistence.
| |

|`+expose+` _<<exposeconfig, ExposeConfig>>_ |Expose specifies options
for exposing the API server.By default, it’s only exposed as a
ClusterIP. | |

|`+nodeSelector+` _object (keys:string, values:string)_ |NodeSelector
specifies node labels to constrain where server/agent pods are
scheduled.In "`shared`" mode, this also applies to workloads. | |

|`+priorityClass+` _string_ |PriorityClass specifies the
priorityClassName for server/agent pods.In "`shared`" mode, this also
applies to workloads. | |

|`+tokenSecretRef+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#secretreference-v1-core[SecretReference]_
|TokenSecretRef is a Secret reference containing the token used by
worker nodes to join the cluster.The Secret must have a "`token`" field
in its data. | |

|`+tlsSANs+` _string array_ |TLSSANs specifies subject alternative names
for the K3s server certificate. | |

|`+serverArgs+` _string array_ |ServerArgs specifies ordered key-value
pairs for K3s server pods.Example: ["`–tls-san=example.com`"] | |

|`+agentArgs+` _string array_ |AgentArgs specifies ordered key-value
pairs for K3s agent pods.Example: ["`–node-name=my-agent-node`"] | |

|`+serverEnvs+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#envvar-v1-core[EnvVar]
array_ |ServerEnvs specifies list of environment variables to set in the
server pod. | |

|`+agentEnvs+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#envvar-v1-core[EnvVar]
array_ |AgentEnvs specifies list of environment variables to set in the
agent pod. | |

|`+addons+` _<<addon, Addon>> array_ |Addons specifies secrets
containing raw YAML to deploy on cluster startup. | |

|`+serverLimit+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#resourcelist-v1-core[ResourceList]_
|ServerLimit specifies resource limits for server nodes. | |

|`+workerLimit+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#resourcelist-v1-core[ResourceList]_
|WorkerLimit specifies resource limits for agent nodes. | |

|`+mirrorHostNodes+` _boolean_ |MirrorHostNodes controls whether node
objects from the host clusterare mirrored into the virtual cluster. | |

|`+customCAs+` _<<customcas, CustomCAs>>_ |CustomCAs specifies the
cert/key pairs for custom CA certificates. | |

|`+sync+` _<<syncconfig, SyncConfig>>_ |Sync specifies the resources
types that will be synced from virtual cluster to host cluster. |{ } |
|===

===== ConfigMapSyncConfig

ConfigMapSyncConfig specifies the sync options for services.

_Appears in:_ - <<syncconfig, SyncConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+enabled+` _boolean_ |Enabled is an on/off switch for syncing
resources. |true |

|`+selector+` _object (keys:string, values:string)_ |Selector specifies
set of labels of the resources that will be synced, if emptythen all
resources of the given type will be synced. | |
|===

===== CredentialSource

CredentialSource defines where to get a credential from. It can
represent either a TLS key pair or a single private key.

_Appears in:_ - <<credentialsources, CredentialSources>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+secretName+` _string_ |SecretName specifies the name of an existing
secret to use.The controller expects specific keys inside based on the
credential type:- For TLS pairs (e.g., ServerCA): '`tls.crt`' and
'`tls.key`'.- For ServiceAccountTokenKey: '`tls.key`'. | |
|===

===== CredentialSources

CredentialSources lists all the required credentials, including both TLS
key pairs and single signing keys.

_Appears in:_ - <<customcas, CustomCAs>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+serverCA+` _<<credentialsource, CredentialSource>>_ |ServerCA
specifies the server-ca cert/key pair. | |

|`+clientCA+` _<<credentialsource, CredentialSource>>_ |ClientCA
specifies the client-ca cert/key pair. | |

|`+requestHeaderCA+` _<<credentialsource, CredentialSource>>_
|RequestHeaderCA specifies the request-header-ca cert/key pair. | |

|`+etcdServerCA+` _<<credentialsource, CredentialSource>>_ |ETCDServerCA
specifies the etcd-server-ca cert/key pair. | |

|`+etcdPeerCA+` _<<credentialsource, CredentialSource>>_ |ETCDPeerCA
specifies the etcd-peer-ca cert/key pair. | |

|`+serviceAccountToken+` _<<credentialsource, CredentialSource>>_
|ServiceAccountToken specifies the service-account-token key. | |
|===

===== CustomCAs

CustomCAs specifies the cert/key pairs for custom CA certificates.

_Appears in:_ - <<clusterspec, ClusterSpec>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+enabled+` _boolean_ |Enabled toggles this feature on or off. |true |

|`+sources+` _<<credentialsources, CredentialSources>>_ |Sources defines
the sources for all required custom CA certificates. | |
|===

===== ExposeConfig

ExposeConfig specifies options for exposing the API server.

_Appears in:_ - <<clusterspec, ClusterSpec>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+ingress+` _<<ingressconfig, IngressConfig>>_ |Ingress specifies
options for exposing the API server through an Ingress. | |

|`+loadBalancer+` _<<loadbalancerconfig, LoadBalancerConfig>>_
|LoadBalancer specifies options for exposing the API server through a
LoadBalancer service. | |

|`+nodePort+` _<<nodeportconfig, NodePortConfig>>_ |NodePort specifies
options for exposing the API server through NodePort. | |
|===

===== IngressConfig

IngressConfig specifies options for exposing the API server through an
Ingress.

_Appears in:_ - <<exposeconfig, ExposeConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+annotations+` _object (keys:string, values:string)_ |Annotations
specifies annotations to add to the Ingress. | |

|`+ingressClassName+` _string_ |IngressClassName specifies the
IngressClass to use for the Ingress. | |
|===

===== IngressSyncConfig

IngressSyncConfig specifies the sync options for services.

_Appears in:_ - <<syncconfig, SyncConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+enabled+` _boolean_ |Enabled is an on/off switch for syncing
resources. |false |

|`+selector+` _object (keys:string, values:string)_ |Selector specifies
set of labels of the resources that will be synced, if emptythen all
resources of the given type will be synced. | |
|===

===== LoadBalancerConfig

LoadBalancerConfig specifies options for exposing the API server through
a LoadBalancer service.

_Appears in:_ - <<exposeconfig, ExposeConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+serverPort+` _integer_ |ServerPort is the port on which the K3s
server is exposed when type is LoadBalancer.If not specified, the
default https 443 port will be allocated.If 0 or negative, the port will
not be exposed. | |

|`+etcdPort+` _integer_ |ETCDPort is the port on which the ETCD service
is exposed when type is LoadBalancer.If not specified, the default etcd
2379 port will be allocated.If 0 or negative, the port will not be
exposed. | |
|===

===== NodePortConfig

NodePortConfig specifies options for exposing the API server through
NodePort.

_Appears in:_ - <<exposeconfig, ExposeConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+serverPort+` _integer_ |ServerPort is the port on each node on which
the K3s server is exposed when type is NodePort.If not specified, a
random port between 30000-32767 will be allocated.If out of range, the
port will not be exposed. | |

|`+etcdPort+` _integer_ |ETCDPort is the port on each node on which the
ETCD service is exposed when type is NodePort.If not specified, a random
port between 30000-32767 will be allocated.If out of range, the port
will not be exposed. | |
|===

===== PersistenceConfig

PersistenceConfig specifies options for persisting etcd data.

_Appears in:_ - <<clusterspec, ClusterSpec>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+type+` _<<persistencemode, PersistenceMode>>_ |Type specifies the
persistence mode. |dynamic |

|`+storageClassName+` _string_ |StorageClassName is the name of the
StorageClass to use for the PVC.This field is only relevant in
"`dynamic`" mode. | |

|`+storageRequestSize+` _string_ |StorageRequestSize is the requested
size for the PVC.This field is only relevant in "`dynamic`" mode. |2G |
|===

===== PersistenceMode

_Underlying type:_ _string_

PersistenceMode is the storage mode of a Cluster.

_Appears in:_ - <<persistenceconfig, PersistenceConfig>>

===== PersistentVolumeClaimSyncConfig

PersistentVolumeClaimSyncConfig specifies the sync options for services.

_Appears in:_ - <<syncconfig, SyncConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+enabled+` _boolean_ |Enabled is an on/off switch for syncing
resources. |true |

|`+selector+` _object (keys:string, values:string)_ |Selector specifies
set of labels of the resources that will be synced, if emptythen all
resources of the given type will be synced. | |
|===

===== PodSecurityAdmissionLevel

_Underlying type:_ _string_

PodSecurityAdmissionLevel is the policy level applied to the pods in the
namespace.

_Validation:_ - Enum: [privileged baseline restricted]

_Appears in:_ - <<virtualclusterpolicyspec, VirtualClusterPolicySpec>>

===== PriorityClassSyncConfig

PriorityClassSyncConfig specifies the sync options for services.

_Appears in:_ - <<syncconfig, SyncConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+enabled+` _boolean_ |Enabled is an on/off switch for syncing
resources. |false |

|`+selector+` _object (keys:string, values:string)_ |Selector specifies
set of labels of the resources that will be synced, if emptythen all
resources of the given type will be synced. | |
|===

===== SecretSyncConfig

SecretSyncConfig specifies the sync options for services.

_Appears in:_ - <<syncconfig, SyncConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+enabled+` _boolean_ |Enabled is an on/off switch for syncing
resources. |true |

|`+selector+` _object (keys:string, values:string)_ |Selector specifies
set of labels of the resources that will be synced, if emptythen all
resources of the given type will be synced. | |
|===

===== ServiceSyncConfig

ServiceSyncConfig specifies the sync options for services.

_Appears in:_ - <<syncconfig, SyncConfig>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+enabled+` _boolean_ |Enabled is an on/off switch for syncing
resources. |true |

|`+selector+` _object (keys:string, values:string)_ |Selector specifies
set of labels of the resources that will be synced, if emptythen all
resources of the given type will be synced. | |
|===

===== SyncConfig

SyncConfig will contain the resources that should be synced from virtual
cluster to host cluster.

_Appears in:_ - <<clusterspec, ClusterSpec>> -
<<virtualclusterpolicyspec, VirtualClusterPolicySpec>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+services+` _<<servicesyncconfig, ServiceSyncConfig>>_ |Services
resources sync configuration. |{ enabled:true } |

|`+configMaps+` _<<configmapsyncconfig, ConfigMapSyncConfig>>_
|ConfigMaps resources sync configuration. |{ enabled:true } |

|`+secrets+` _<<secretsyncconfig, SecretSyncConfig>>_ |Secrets resources
sync configuration. |{ enabled:true } |

|`+ingresses+` _<<ingresssyncconfig, IngressSyncConfig>>_ |Ingresses
resources sync configuration. |{ enabled:false } |

|`+persistentVolumeClaims+`
_<<persistentvolumeclaimsyncconfig, PersistentVolumeClaimSyncConfig>>_
|PersistentVolumeClaims resources sync configuration. |{ enabled:true }
|

|`+priorityClasses+`
_<<priorityclasssyncconfig, PriorityClassSyncConfig>>_ |PriorityClasses
resources sync configuration. |{ enabled:false } |
|===

===== VirtualClusterPolicy

VirtualClusterPolicy allows defining common configurations and
constraints for clusters within a clusterpolicy.

_Appears in:_ - <<virtualclusterpolicylist, VirtualClusterPolicyList>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+apiVersion+` _string_ |`+k3k.io/v1beta1+` | |

|`+kind+` _string_ |`+VirtualClusterPolicy+` | |

|`+metadata+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#objectmeta-v1-meta[ObjectMeta]_
|Refer to Kubernetes API documentation for fields of `+metadata+`. | |

|`+spec+` _<<virtualclusterpolicyspec, VirtualClusterPolicySpec>>_ |Spec
defines the desired state of the VirtualClusterPolicy. |{ } |
|===

===== VirtualClusterPolicyList

VirtualClusterPolicyList is a list of VirtualClusterPolicy resources.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+apiVersion+` _string_ |`+k3k.io/v1beta1+` | |

|`+kind+` _string_ |`+VirtualClusterPolicyList+` | |

|`+metadata+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#listmeta-v1-meta[ListMeta]_
|Refer to Kubernetes API documentation for fields of `+metadata+`. | |

|`+items+` _<<virtualclusterpolicy, VirtualClusterPolicy>> array_ | | |
|===

===== VirtualClusterPolicySpec

VirtualClusterPolicySpec defines the desired state of a
VirtualClusterPolicy.

_Appears in:_ - <<virtualclusterpolicy, VirtualClusterPolicy>>

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Field |Description |Default |Validation
|`+quota+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#resourcequotaspec-v1-core[ResourceQuotaSpec]_
|Quota specifies the resource limits for clusters within a
clusterpolicy. | |

|`+limit+`
_https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#limitrangespec-v1-core[LimitRangeSpec]_
|Limit specifies the LimitRange that will be applied to all pods within
the VirtualClusterPolicyto set defaults and constraints (min/max) | |

|`+defaultNodeSelector+` _object (keys:string, values:string)_
|DefaultNodeSelector specifies the node selector that applies to all
clusters (server + agent) in the target Namespace. | |

|`+defaultPriorityClass+` _string_ |DefaultPriorityClass specifies the
priorityClassName applied to all pods of all clusters in the target
Namespace. | |

|`+allowedMode+` _<<clustermode, ClusterMode>>_ |AllowedMode specifies
the allowed cluster provisioning mode. Defaults to "`shared`". |shared
|Enum: [shared virtual]

|`+disableNetworkPolicy+` _boolean_ |DisableNetworkPolicy indicates
whether to disable the creation of a default network policy for cluster
isolation. | |

|`+podSecurityAdmissionLevel+`
_<<podsecurityadmissionlevel, PodSecurityAdmissionLevel>>_
|PodSecurityAdmissionLevel specifies the pod security admission level
applied to the pods in the namespace. | |Enum: [privileged baseline
restricted]

|`+sync+` _<<syncconfig, SyncConfig>>_ |Sync specifies the resources
types that will be synced from virtual cluster to host cluster. |{ } |
|===
