#!/bin/bash

set -eou pipefail

DOCS_DIR=./docs/cli


go run $DOCS_DIR/genclidoc.go

echo "Converting Markdown documentation to asciidoc"

pandoc --from markdown --to asciidoc --lua-filter=$DOCS_DIR/convert.lua $DOCS_DIR/k3kcli.md > $DOCS_DIR/k3kcli.adoc
echo "" >> $DOCS_DIR/k3kcli.adoc
pandoc --from markdown --to asciidoc --lua-filter=$DOCS_DIR/convert.lua $DOCS_DIR/k3kcli_*.md >> $DOCS_DIR/k3kcli.adoc

echo "Asciidoc documentation generated at $DOCS_DIR/k3kcli.adoc"
