#!/bin/bash
set -ex

source $(dirname $0)/version

cd $(dirname $0)/..

git fetch --tags
CHART_TAG=chart-$(grep "version: " charts/k3k/Chart.yaml | awk '{print $2}')
if [ $(git tag -l "$version") ]; then
    echo "tag already exists"
    exit 1
fi

# update the index.yaml
cr index  --token ${GITHUB_TOKEN} \
          --release-name-template "chart-{{ .Version }}" \
          --package-path ./deploy/ \
          --index-path index.yaml \
          --git-repo k3k \
          -o rancher

# push to gh-pages
git config --global user.email "drone[bot]@users.noreply.github.com"
git config --global user.name "drone[bot]"
git add index.yaml
git commit -m "add chart-${CHART_TAG} to index.yaml"
git push --set-upstream origin HEAD:gh-pages
