#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"


if [[ $TAG = "chart*" ]]; then
  TAG=${TAG:-${VERSION}}
else 
  TAG=${TAG:-${VERSION}${SUFFIX}}
fi

REPO=${REPO:-rancher}

if echo $TAG | grep dirty; then
    TAG=dev
fi
