# registry.suse.com/bci/bci-base:15.7
FROM registry.suse.com/bci/bci-base@sha256:94069e4c701fc5c4d38d8f1c25ab2a80c0da89320a6d622efc1bd57fd16769a2

ARG BIN_K3K=bin/k3k
ARG BIN_K3KCLI=bin/k3kcli

COPY ${BIN_K3K} /usr/bin/
COPY ${BIN_K3KCLI} /usr/bin/

CMD ["k3k"]
