# TODO: swicth this to BCI-micro or scratch. Left as base right now so that debug can be done a bit easier
FROM registry.suse.com/bci/bci-base:15.6

ARG BIN_K3K_KUBELET=bin/k3k-kubelet

COPY ${BIN_K3K_KUBELET} /usr/bin/

ENTRYPOINT ["/usr/bin/k3k-kubelet"]
