# TODO: swicth this to BCI-micro or scratch. Left as base right now so that debug can be done a bit easier
FROM registry.suse.com/bci/bci-base:15.6

COPY bin/k3k-kubelet /usr/bin/

ENTRYPOINT ["/usr/bin/k3k-kubelet"]
