on:
  push:
    tags:
    - "chart-*"

env:
    GH_TOKEN: ${{ github.token }}

name: Chart
permissions:
    contents: write
    id-token: write
jobs:
  chart-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Package Chart
      run: |
        make package-chart;

    - name: Release Chart
      run: |
        gh release upload ${{ github.ref_name }} deploy/*
      
    - name: Index Chart
      run: |
        make index-chart
        