on:
  push:
    tags:
    - "chart-*"

name: Chart
permissions:
    contents: write
    id-token: write
jobs:
  chart-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Package Chart
      run: |
        make package-chart;

    - name: Release Chart
      uses: softprops/action-gh-release@v2
      with:
        files: |
          deploy/*
      
    - name: Index Chart
      run: |
        make index-chart
        