name: Chart

on:
  workflow_dispatch:
  push:
    tags:
    - "chart-*"

permissions:
    contents: write

jobs:
  chart-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Check tag
      if: github.event_name == 'push'
      run: |
        pushed_tag=$(echo ${{ github.ref_name }} | sed "s/chart-//")
        chart_tag=$(yq .version charts/k3k/Chart.yaml)
        
        echo pushed_tag=${pushed_tag} chart_tag=${chart_tag}
        [ "${pushed_tag}" == "${chart_tag}" ]

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
    - name: Install Helm
      uses: azure/setup-helm@v4
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        config: .cr.yaml
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
