name: Validate

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
      with:
        go-version-file: go.mod
        cache: true

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Run linters
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: v2.12.2
        args: -v
        only-new-issues: true
        skip-cache: false

    - name: Run formatters
      run: golangci-lint -v fmt ./...

    - name: Lint YAML
      run: |
        pipx install yamllint==1.38.0
        make lint-yaml

    - name: Validate
      run: make validate
